{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "pmu-simulator.fullname" . }}
  labels:
    {{ include "pmu-simulator.labels" . | nindent 4 }}
spec:
  namespaceSelector: { }
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
  selector:
    matchLabels:
      {{ include "pmu-simulator.selectorLabels" . | nindent 6 }}
    {{- with .Values.monitoring.podMonitorMetricRelabelings }}
      metricRelabelings:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.monitoring.podMonitorRelabelings }}
      relabelings:
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
